### ISSUE TITLE
UnicodeDecodeError when load stopwords

### ISSUE THREAD

**Issue by inuyasha2012** [huyingxi/Synonyms#12]
我加了encoding才避免了UnicodeDecodeError，用的python3
words = open(file_path, 'r'， encoding='utf-8')

__init__文件第107行

**Comment by Samurais** [comment]
Which version are you using? Could  you create a pull request? Thanks.

**Comment by Samurais** [comment]
在发布之前，我会在Python2和Python3中（Mac OSX），运行
```
python demo.py
```
保证没有问题后才发布。
你用的是什么OS?

**Comment by inuyasha2012** [comment]
用windows 10出的问题

**Comment by Samurais** [comment]
merge PR https://github.com/huyingxi/Synonyms/pull/13
