### ISSUE TITLE
"import synonyms" error 

### ISSUE THREAD

**Issue by shinalone** [huyingxi/Synonyms#17]
# description
import synonyms
>> Synonyms on loading vocab ...
>> Synonyms on loading stopwords ...
Traceback (most recent call last):
  File "C:\Install\Anaconda35\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-e6c3357df047>", line 1, in <module>
    import synonyms
  File "C:\Install\PyCharm 2017.2.4\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Install\Anaconda35\lib\site-packages\synonyms\__init__.py", line 113, in <module>
    _load_stopwords(_fin_stopwords_path)
  File "C:\Install\Anaconda35\lib\site-packages\synonyms\__init__.py", line 108, in _load_stopwords
    stopwords = words.readlines()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x8a in position 2: illegal multibyte sequence

# environment
windows10,64bit

* version:
C:\Users\shina>pip install -i https://pypi.doubanio.com/simple/ synonyms
Collecting synonyms
  Downloading https://pypi.doubanio.com/packages/2a/70/47abca5e6a5b1cc695c3df662b97b4c50aff343f75bdebb316ceb5d18205/synonyms-1.9.tar.gz (61.5MB)
    100% |████████████████████████████████| 61.5MB 3.2MB/s
Requirement already satisfied: jieba>=0.39 in c:\install\anaconda35\lib\site-packages (from synonyms)
Requirement already satisfied: numpy>=1.13.1 in c:\install\anaconda35\lib\site-packages (from synonyms)
Building wheels for collected packages: synonyms
  Running setup.py bdist_wheel for synonyms ... done
  Stored in directory: C:\Users\shina\AppData\Local\pip\Cache\wheels\d3\8d\ee\b32007051068368229e14a41e936a7143bdf6e8711ee4be5b8
Successfully built synonyms
Installing collected packages: synonyms
Successfully installed synonyms-1.9

# Please help, thank you.

**Comment by Samurais** [comment]
py3 设置环境变量：PYTHONIOENCODING=utf-8。
参考 http://m.blog.csdn.net/liuyukuan/article/details/50855748
