### ISSUE TITLE
Would you consider adding support for jieba otherthan word2vec?

### ISSUE THREAD

**Issue by Charliechen1** [huyingxi/Synonyms#19]
# description
Under my trial to your impressive project, I found everything exciting except one thing: I haven't found any API to add my own words to the dictionary

As jieba supports more efficiently for Chinese semantics analysis, and it allow user to add their own words to the dictionary, therefore, would you consider to add support to that?

Thank you very much.

* version:
The commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
If you look into Jieba, it does not have synonyms, it is just a tokenizer. Jieba's analysis interfaces are using textrank, it is totally different what we want to solve in ```Synonyms```. Synonyms is a semantic package with training with large dataset. The scores are computed as probabilities, I also wonder if we can have a way to tune the words post training from word2vec. I also have the requirements, but now, we haven't find a great approach, as this requirement is duplicated with #8, it is closed.

Duplicated with #8 .
