### ISSUE TITLE
pip version not fix python3 open stopwords file UnicodeDecodeError bug

### ISSUE THREAD

**Issue by caomaocao** [huyingxi/Synonyms#20]
# description
pip version is 1.9 https://pypi.python.org/pypi/synonyms/1.9. I installed it in my Mac 10.13.2 and run script on Python 3.5.3, I found  UnicodeDecodeError . 
## current
I noticed that there was a request fixed the bug in 8 Nov.

## expected
So I suggest u to upload the new version to pip .
# solution

# environment
Mac OS 13.2
Python 3.5.3
* version:
The commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
Thanks, would roll out by this weekend.

**Comment by Samurais** [comment]
fixed by v2.
