### ISSUE TITLE
请问words.nearby.json.gz 这个临近词的词典是怎么学出来的啊，万分感谢

### ISSUE THREAD

**Issue by waterzxj** [huyingxi/Synonyms#23]
# description

## expected

# solution

# environment

* version:
The commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
1) 保证高质量的数据，2) 多尝试。

#21 这里有分享。

其实，我现在有在思考，在训练后，如果进一步的优化。

**Comment by Samurais** [comment]
1) 保证高质量的数据，2) 多尝试。

#21 这里有分享。

其实，我现在有在思考，在训练后，如果进一步的优化。
