### ISSUE TITLE
请问words.nearby.json.gz这个词典的数据是怎么生成的啊，万分感谢

### ISSUE THREAD

**Issue by waterzxj** [huyingxi/Synonyms#25]
# description

## expected

# solution

# environment

* version:
The commit hash (`git rev-parse HEAD`)

**Comment by 1056739724** [comment]
我也想知道

**Comment by Samurais** [comment]
#22

**Comment by 1056739724** [comment]
是在word2vec的基础上做了什么？另外看了一下同义词表，效果不太满意，是否有优化方式～
