### ISSUE TITLE
I would call these similar words, or contextually related words.

### ISSUE THREAD

**Issue by jiangweiatgithub** [huyingxi/Synonyms#26]
# description

## expected

# solution

# environment

* version:
The commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
https://www.zhihu.com/question/21030556/answer/247794414

![image](https://user-images.githubusercontent.com/3538629/35056536-12ecb58c-fbed-11e7-937f-be6df21eeaeb.png)
