### ISSUE TITLE
_fin_path is an undefined name in synonyms/data.py

### ISSUE THREAD

**Issue by cclauss** [huyingxi/Synonyms#31]
Where is ___fin_path__ defined?

flake8 testing of https://github.com/huyingxi/Synonyms

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./synonyms/data.py:58:27: F821 undefined name '_fin_path'
                gzip.open(_fin_path)),
                          ^
./synonyms/data.py:62:26: F821 undefined name '_fin_path'
        _fin = gzip.open(_fin_path, 'rt', encoding='utf-8', errors="ignore")
                         ^
```

**Comment by Samurais** [comment]
Actually, data.py is some deprecated code snippets, but I don't want to remove them, so data.py is never used, I think we should better rename this file. Great thanks.
