### ISSUE TITLE
两个句子的相似度比较结果和readme中的数字不符？

### ISSUE THREAD

**Issue by JuntingGuo** [huyingxi/Synonyms#32]
# description
用demo中的几个句子测试了一下，发现和readme中给出的结果不一致。

## current
旗帜引领方向 vs 道路决定命运: 0.218
旗帜引领方向 vs 旗帜指引道路: 0.353
发生历史性变革 vs 发生历史性变革: 1.0

## expected
旗帜引领方向 vs 道路决定命运: 0.429
旗帜引领方向 vs 旗帜指引道路: 0.93
发生历史性变革 vs 发生历史性变革: 1.0
# solution

# environment
python 2.7
* version:
013fa8dba82bf3501600989882948d7a3f57271c

**Comment by Samurais** [comment]
是的，现在README. md中的分数是之前版本的，#14 引入了编辑距离，分数有变化。

https://github.com/huyingxi/Synonyms/issues/14

现在的分数比之前的底一些，这部分会在春节期间给出新的评测，我们使用的数据集 https://github.com/fssqawj/SentenceSim/blob/master/dev.txt 也没有支持足够多的场景。

这方面，有没有开放的用于中文近似度评测的数据集？

**Comment by JuntingGuo** [comment]
在之前的版本中的句子相似度计算是单纯的使用了欧几里得距离，效果比加入编辑距离的更好对吗？
暂时我也没有找到相关的数据集，我这边也在寻找，如果有找到的会回来添加。
谢谢你的回复。

**Comment by Samurais** [comment]
最新的优化结果在 #43 中。
v2.5 优化了编辑距离，通过向量相近的单词和平滑策略，使得结果更合理。
