### ISSUE TITLE
相似度计算：横向对比

### ISSUE THREAD

**Issue by Samurais** [huyingxi/Synonyms#33]
# description
https://github.com/yaleimeng/Final_word_Similarity

## expected

# solution

# environment

* version:
The commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
用几个词做了比较，结果如下：
![image](https://user-images.githubusercontent.com/3538629/35482707-4da4fa2e-0474-11e8-875d-852cae809ec2.png)

**Comment by catqaq** [comment]
hi, 非常棒的工作，非常感谢！我想问下人工标准的部分有相关的数据集吗？还是说只标注了少量case？
