### ISSUE TITLE
AssertionError: seg len should be 2

### ISSUE THREAD

**Issue by babyhuzi111** [huyingxi/Synonyms#4]
File "/home/*/anaconda3/lib/python3.6/site-packages/synonyms/__init__.py", line 184, in compare
    w2, t2 = _segment_words(s2)
  File "/home/*/anaconda3/lib/python3.6/site-packages/synonyms/__init__.py", line 150, in _segment_words
    assert len(_) == 2, "seg len should be 2"
AssertionError: seg len should be 2
I don't know why it has this problem?

**Comment by Samurais** [comment]
This would happen when you try to compare none Chinese sentences, as the tokenizer only supports Chinese for now. 
Have a look at  
https://github.com/huyingxi/Synonyms/blob/6d7541208906838652c0ea89eedf1af360816e2a/synonyms/__init__.py#L154

But it is welcomed to support more language with multi-languages vectors in word2vec format.

Can you tell me more about your user scenario? What is your input for synonyms#compare ? It is not in Chinese?

**Comment by babyhuzi111** [comment]
thank you for your explain. yes, i deal with a text contain chinese  and english. when i input like 
sent1 = '5、服务广大汽车消费者，便于选车购车'
sent2 = '《if you 》'
count = synonyms.compare(sent1, sent2)
it will has mistake. 
however,when i change sent2 to '《 you 》'
it can work,the score is 0. so i don't know why?
i want to use it to judge the similarity of two sentences, however it run a bit snow , it spend about 12 hours to run about 100000 pair sentences.

**Comment by Samurais** [comment]
It needs more efforts to enhance the similarity api, I would like to implement some DistanceMeasure methods for better quality, such as Chebyshev Distance. This would be done in future.

**Comment by Samurais** [comment]
The enhancement would be done with #6, compare interface would be refactored.
