### ISSUE TITLE
载入vocab.txt报错

### ISSUE THREAD

**Issue by xiaoniuzilo** [huyingxi/Synonyms#46]
`>>> import synonyms
>> Synonyms load wordseg dict [D:\python34\lib\site-packages\synonyms\data\vocab
.txt] ...
Traceback (most recent call last):
  File "D:\python34\lib\site-packages\jieba\posseg\__init__.py", line 105, in lo
ad_word_tag
    word, _, tag = line.split(" ")
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\python34\lib\site-packages\synonyms\__init__.py", line 85, in <module
>
    _tokenizer.initialize(tokenizer_dict)
  File "D:\python34\lib\site-packages\jieba\posseg\__init__.py", line 95, in ini
tialize
    self.load_word_tag(self.tokenizer.get_dict_file())
  File "D:\python34\lib\site-packages\jieba\posseg\__init__.py", line 109, in lo
ad_word_tag
    'invalid POS dictionary entry in %s at Line %s: %s' % (f_name, lineno, line)
)
ValueError: invalid POS dictionary entry in D:\python34\lib\site-packages\synony
ms\data\vocab.txt at Line 333405: 福荫 1 v 2 n`

好像是jieba不支持多个词性，后来手工修改，每个词只保留一个词性，就没有这个bug了

**Comment by Samurais** [comment]
那可以帮忙提交一下修改后的vocab.txt么？创建一个Pull Request. Thanks.

**Comment by Samurais** [comment]
还有一个方案，可以不改变词典的方式，快速解决。一会提交。

**Comment by Samurais** [comment]
问题在 synonyms-3.3.5中解决，请再试试。 
https://pypi.python.org/pypi/synonyms/3.3.5

**Comment by xiaoniuzilo** [comment]
initialize dictionary: None| initialized: False
Building prefix dict from the default dictionary ...
Traceback (most recent call last):
  File "word2vec.py", line 59, in <module>
    r = synonyms.compare(sen1, sen2, seg=True)
  File "D:\python34\lib\site-packages\synonyms-3.3.5-py3.4.egg\synonyms\__init__
.py", line 276, in compare
    s1 = [x for x in jieba.cut(s1)]
  File "D:\python34\lib\site-packages\synonyms-3.3.5-py3.4.egg\synonyms\__init__
.py", line 276, in <listcomp>
    s1 = [x for x in jieba.cut(s1)]
  File "D:\python34\lib\site-packages\synonyms-3.3.5-py3.4.egg\synonyms\jieba\__
init__.py", line 304, in cut
    for word in cut_block(blk):
  File "D:\python34\lib\site-packages\synonyms-3.3.5-py3.4.egg\synonyms\jieba\__
init__.py", line 236, in __cut_DAG
    DAG = self.get_DAG(sentence)
  File "D:\python34\lib\site-packages\synonyms-3.3.5-py3.4.egg\synonyms\jieba\__
init__.py", line 182, in get_DAG
    self.check_initialized()
  File "D:\python34\lib\site-packages\synonyms-3.3.5-py3.4.egg\synonyms\jieba\__
init__.py", line 171, in check_initialized
    self.initialize()
  File "D:\python34\lib\site-packages\synonyms-3.3.5-py3.4.egg\synonyms\jieba\__
init__.py", line 145, in initialize
    self.FREQ, self.total = self.gen_pfdict(self.get_dict_file())
  File "D:\python34\lib\site-packages\synonyms-3.3.5-py3.4.egg\synonyms\jieba\__
init__.py", line 355, in get_dict_file
    return get_module_res(DEFAULT_DICT_NAME)
  File "D:\python34\lib\site-packages\synonyms-3.3.5-py3.4.egg\synonyms\jieba\_c
ompat.py", line 8, in <lambda>
    os.path.join(*res))
  File "D:\python34\lib\site-packages\pkg_resources.py", line 886, in resource_s
tream
    self, resource_name
  File "D:\python34\lib\site-packages\pkg_resources.py", line 1411, in get_resou
rce_stream
    return open(self._fn(self.module_path, resource_name), 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\python34\\lib\\site
-packages\\synonyms-3.3.5-py3.4.egg\\synonyms\\jieba\\dict.txt'


jieba里面漏了词典。。。

**Comment by Samurais** [comment]
这个字典是故意删除的，以减少体积。
我本地测试没有问题，你是怎么执行的？

**Comment by xiaoniuzilo** [comment]
查近义词没有问题，但是执行r=synonyms.compare(sen1, sen2, seg=True)的时候报错

**Comment by Samurais** [comment]
![image](https://user-images.githubusercontent.com/3538629/36972262-721cb170-20a9-11e8-98e7-a26a6ad046dc.png)
这是我的控制台输出，您再帮忙测试一下。

@xiaoniuzilo

**Comment by xiaoniuzilo** [comment]
![_20180307095707](https://user-images.githubusercontent.com/25164899/37069411-34555114-21ab-11e8-93fb-a0415fa67427.png)
![_20180307095739](https://user-images.githubusercontent.com/25164899/37069422-3bd0f29a-21ab-11e8-9fe0-da8b7c79ae94.png)

这是我的控制台输出。我试了3.3.5和3.3.6，还是不行

**Comment by Samurais** [comment]
我是在Mac OSX 上测试的，python版本也是3.6，您能升级一下 python么？
您现在用的是3.4， 目前Synonyms 会兼容py2.7和py3.6。
Synonyms不会兼容到py3.4。

**Comment by xiaoniuzilo** [comment]
我原先的系统项目用的依赖包装的太多了，不好升级python。
后来用64位的windows（没装过python）装了python3.6.0，装完synonyms以后，import synonyms就报错，然后发现是缺少jieba（requires里面没有jieba），又装了jieba，再运行，还是原来一样的错。

这是没装jieba的时候，import即报错
![_20180307112540](https://user-images.githubusercontent.com/25164899/37072296-9021bc46-21b8-11e8-8afa-7d2b401d487e.png)

装完jieba，compare报错
![new1](https://user-images.githubusercontent.com/25164899/37072309-a3f43190-21b8-11e8-9e25-fa93c37e71b0.png)
![new2](https://user-images.githubusercontent.com/25164899/37072316-a9eec812-21b8-11e8-8fa2-e8f0059bf35d.png)

您可以试一下在新的环境下安装3.3.6的synonyms运行看下会不会出错么？可能原先的环境配置、依赖包什么的已经很全了所以没有问题。。

原先的版本python 3.4是兼容的。。我先用回原先的版本

**Comment by Shaun-Chen** [comment]
我也遇到了同样的问题

**Comment by xiaoniuzilo** [comment]
所以我需要放个dict.txt到这个目录下面么？ 这个dict.txt去哪找呢？

**Comment by xiaoniuzilo** [comment]
![_20180307170933](https://user-images.githubusercontent.com/25164899/37084737-34cbe212-21eb-11e8-855d-b2ed94e20e72.png)

更新到3.3.7后，出现了新的错误。

问题出在g = cosine(_flat_sum_array(_get_wv(s1)), _flat_sum_array(_get_wv(s2)))这一句上，
我debug了一下，发现_get_wv(s1)返回的是这样的数据
[array([-1.0234414 , -0.91894585,  3.9090822 ,  3.81904   , -3.6037214 ,
       -3.9518602 ,  0.01611492, -1.6388522 , -0.7779308 , -1.6034095 ,
        0.1289268 , -2.8376312 , -3.0469065 ,  0.8355294 ,  0.24044842,
        1.1895255 , -1.1847442 , -1.394092  , -3.2582932 , -1.6245174 ,
       -1.8976773 ,  0.77721745,  0.8999519 ,  1.8871949 , -0.42668143,
        2.9785142 ,  3.4541056 ,  0.73682076,  0.7882158 ,  2.5028892 ,
        0.17661184, -2.3663886 , -0.05921778, -3.4188423 ,  2.281212  ,
       -3.741536  ,  1.9671475 ,  2.3171473 , -3.7670877 ,  0.52188015,
       -0.83777446, -1.0437226 ,  1.2149254 , -2.1102762 , -0.60033345,
       -0.45760787, -1.654604  , -3.246272  ,  0.19051884, -0.32268783,
        1.7110114 , -0.09502684,  0.19144851, -0.7577923 , -2.0900626 ,
       -1.0901747 , -1.4749427 , -0.530201  , -0.6559356 , -0.7915072 ,
        1.8043354 , -0.6007686 , -2.2500143 , -2.1694245 , -1.0805204 ,
        1.8429016 , -2.4611323 , -2.4917428 , -1.067181  , -1.1465319 ,
        0.99313486, -0.7435248 ,  0.22195439, -3.7640219 ,  2.4330814 ,
        1.2659118 , -2.601255  ,  0.3889471 ,  1.0667586 ,  0.19212304,
       -1.3080703 , -1.0984954 ,  1.8812038 ,  2.2239206 , -4.499009  ,
       -1.6243669 , -1.8377169 ,  1.6811581 ,  2.643137  ,  2.4428432 ,
        1.3685721 , -2.704252  , -1.3082669 , -4.737651  ,  2.14909   ,
        3.002403  , -5.065075  ,  2.271011  ,  2.7030985 ,  0.15419313],
      dtype=float32), array([ 2.9995964 ,  0.33439144, -1.2586061 ,  2.4610105 ,  1.476976  ,
       -0.62776846, -2.1438913 , -2.0424268 , -1.7655456 , -0.61853194,
       -0.06430313,  1.8037071 , -1.0377121 ,  0.83014566, -1.1934218 ,
        2.5493886 ,  0.6687687 , -0.5434914 , -0.68210745, -2.2578523 ,
        1.9058156 ,  3.347651  , -1.7887963 , -3.177395  , -3.3820684 ,
        1.9022896 , -1.1350188 ,  0.48965546,  2.4308968 , -0.577411  ,
       -0.9972664 , -0.3755909 ,  0.8760435 , -5.7624264 ,  1.0056597 ,
       -2.263102  , -0.49478045,  1.7476963 , -5.4698496 , -1.2607257 ,
       -0.9386588 , -3.3511388 ,  1.0470109 , -4.275842  , -1.2958093 ,
        0.30241555,  2.2366636 , -4.488514  ,  1.2159871 ,  2.0785518 ,
        3.1161203 ,  0.1719124 , -0.6398507 ,  2.8156228 , -1.4321451 ,
       -0.86007905,  0.20074502, -0.59738845, -0.6245048 , -1.1919745 ,
        2.3080761 ,  1.167786  ,  1.283614  ,  1.5028583 , -2.2622347 ,
       -0.8756886 , -3.07079   , -2.888107  , -1.7801269 , -0.27929604,
       -0.9039806 ,  0.33567858, -0.9299515 , -4.797099  ,  1.5154414 ,
       -2.484193  ,  0.67848307,  0.6207623 ,  0.36425418, -2.370529  ,
       -2.1189184 , -1.8980342 ,  0.52137625, -0.10967983, -1.5518966 ,
        0.17805544, -6.2149997 ,  2.2700632 , -0.13007511,  1.9508965 ,
       -1.8418851 , -1.6851944 , -2.3519516 ,  1.6616119 ,  0.5413495 ,
        1.5059662 , -0.39569867, -1.6549493 ,  1.7639515 , -0.6651172 ],
      dtype=float32)]

_flat_sum_array(_get_wv(s1)）返回的是
 array([ 1.9761549e+00, -5.8455443e-01,  2.6504760e+00,  6.2800503e+00,
       -2.1267452e+00, -4.5796285e+00, -2.1277764e+00, -3.6812792e+00,
       -2.5434763e+00, -2.2219415e+00,  6.4623669e-02, -1.0339241e+00,
       -4.0846186e+00,  1.6656750e+00, -9.5297343e-01,  3.7389140e+00,
       -5.1597553e-01, -1.9375834e+00, -3.9404006e+00, -3.8823698e+00,
        8.1382990e-03,  4.1248684e+00, -8.8884443e-01, -1.2902002e+00,
       -3.8087499e+00,  4.8808041e+00,  2.3190868e+00,  1.2264762e+00,
        3.2191126e+00,  1.9254782e+00, -8.2065457e-01, -2.7419794e+00,
        8.1682575e-01, -9.1812687e+00,  3.2868719e+00, -6.0046377e+00,
        1.4723670e+00,  4.0648437e+00, -9.2369375e+00, -7.3884559e-01,
       -1.7764332e+00, -4.3948612e+00,  2.2619362e+00, -6.3861184e+00,
       -1.8961427e+00, -1.5519232e-01,  5.8205962e-01, -7.7347860e+00,
        1.4065059e+00,  1.7558639e+00,  4.8271317e+00,  7.6885559e-02,
       -4.4840217e-01,  2.0578306e+00, -3.5222077e+00, -1.9502537e+00,
       -1.2741977e+00, -1.1275895e+00, -1.2804403e+00, -1.9834816e+00,
        4.1124115e+00,  5.6701738e-01, -9.6640027e-01, -6.6656625e-01,
       -3.3427551e+00,  9.6721298e-01, -5.5319223e+00, -5.3798499e+00,
       -2.8473079e+00, -1.4258280e+00,  8.9154243e-02, -4.0784621e-01,
       -7.0799708e-01, -8.5611210e+00,  3.9485228e+00, -1.2182813e+00,
       -1.9227719e+00,  1.0097094e+00,  1.4310129e+00, -2.1784060e+00,
       -3.4269886e+00, -2.9965296e+00,  2.4025800e+00,  2.1142406e+00,
       -6.0509057e+00, -1.4463115e+00, -8.0527163e+00,  3.9512212e+00,
        2.5130618e+00,  4.3937397e+00, -4.7331297e-01, -4.3894463e+00,
       -3.6602185e+00, -3.0760388e+00,  2.6904395e+00,  4.5083694e+00,
       -5.4607735e+00,  6.1606181e-01,  4.4670501e+00, -5.1092410e-01],
      dtype=float32)

所以cosine函数报错。。。。。
不知道是啥问题

**Comment by xiaoniuzilo** [comment]
图片老传不了，直接贴代码
>> Synonyms on loading stopwords [C:\PYTHON36\lib\site-packages\synonyms-3.3.7-p
y3.6.egg\synonyms\data\stopwords.txt] ...
>> Synonyms on loading vectors [C:\PYTHON36\lib\site-packages\synonyms-3.3.7-py3
.6.egg\synonyms\data\words.vector] ...
>>> synonyms.compare('这个字典是故意删除的','以减少体积',True)
0.089
>>> synonyms.compare('这个字典是故意删除的','以减少体积',True)
0.089
>>> synonyms.compare('这个字典是故意删除的','可以用就好了',True)
C:\PYTHON36\lib\site-packages\synonyms-3.3.7-py3.6.egg\synonyms\utils.py:246: Ru
ntimeWarning: invalid value encountered in true_divide
  cosine = lambda a, b: dot(a, b)/(norm(a)*norm(b))
C:\PYTHON36\lib\site-packages\synonyms-3.3.7-py3.6.egg\synonyms\synonyms.py:245:
 RuntimeWarning: invalid value encountered in less
  if r < 0: r = abs(r)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\PYTHON36\lib\site-packages\synonyms-3.3.7-py3.6.egg\synonyms\synonyms
.py", line 288, in compare
    return _similarity_distance(s1, s2)
  File "C:\PYTHON36\lib\site-packages\synonyms-3.3.7-py3.6.egg\synonyms\synonyms
.py", line 245, in _similarity_distance
    if r < 0: r = abs(r)
ValueError: The truth value of an array with more than one element is ambiguous.
 Use a.any() or a.all()

更新到3.3.7后，出现了新的错误。
synonyms.compare('这个字典是故意删除的','以减少体积',True)
返回是正确的
synonyms.compare('这个字典是故意删除的','可以用就好了',True)就报错了。
问题出在g = cosine(_flat_sum_array(_get_wv(s1)), _flat_sum_array(_get_wv(s2)))这一句上，
 我debug了一下，s2分词结果是正确的，但是_get_wv(s2)返回的是[]
所以cosine函数报错。。。。。
 不知道是啥问题

**Comment by Samurais** [comment]
Fix in 3.3.10

**Comment by Samurais** [comment]
@xiaoniuzilo 感谢使用并发布问题。
