### ISSUE TITLE
“减少”近义词为什么返回“增加”呢？

### ISSUE THREAD

**Issue by ahomer** [huyingxi/Synonyms#47]
# description
>>> synonyms.display(u'减少')
'减少'近义词：
  1. 减少:1.0
  2. 增加:0.89950454
  3. 降低:0.89796096
  4. 减低:0.83169204
  5. 下降:0.806061
  6. 减小:0.79056865
  7. 提高:0.7783943
  8. 增大:0.76636106
  9. 缩减:0.7424295
  10. 减缓:0.7414519
## expected
反义词应该去掉，否则词义会相反

# solution

# environment

* version:
The commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
类似的情况会出现。现在还没有很好的办法解决。因为两个词是否被看成近义词，是比较他们的上下文。
"增加"和"降低" 二者就有这样的特点。

下一步会考虑一个解决方案。

**Comment by eecrazy** [comment]
synonyms.display("下降")
'下降'近义词：
  1. 下降:1.0
  2. 上升:0.9347954
  3. 升高:0.8405261
  4. 下滑:0.8240376
  5. 增高:0.81240773
  6. 回升:0.8078515
  7. 减少:0.806061
  8. 降低:0.80133665
  9. 急剧下降:0.7724957
  10. 攀升:0.7713177

所以仅仅根据word2vec得到的近义词，对动词的效果很差，因为它并不区分语义，用法相同的词都被当成了近义词。

**Comment by MingleiLI** [comment]
感觉这个并不应该被称为Synonyms包，因为基于词向量是不能保证得到同义词的，只能得到语义相关的词

**Comment by Samurais** [comment]
# duplicated with #26
