### ISSUE TITLE
3.3.9版本，#51 bug仍然存在

### ISSUE THREAD

**Issue by Shaun-Chen** [huyingxi/Synonyms#52]
# description
查看源码发现，try后g值仍然为无法找到向量，但是其并为出错，所以g仍然为向量nan值，而不会为0，导致计算出错
## expected

# solution

# environment

* version:3.3.9
The commit hash (`git rev-parse HEAD`)

**Comment by Shaun-Chen** [comment]
我在源码做了如下更改：
# g = 0.0
    try:
        g = cosine(_flat_sum_array(_get_wv(s1)), _flat_sum_array(_get_wv(s2)))
    except: pass
    try:
        g_nan_num = np.isnan(g).sum()
        if g_nan_num == 100:
            g = 0.0
    except:
        pass
之后运行可以成功，不知道是否符合您的开发思路

**Comment by Shaun-Chen** [comment]
如果符合的话，我是否可以提供一个pull request？

**Comment by Samurais** [comment]
好的，你先提一下。

**Comment by Shaun-Chen** [comment]
已经提交了
