### ISSUE TITLE
飞碟的同义词怎么会有多个类型的词汇？

### ISSUE THREAD

**Issue by liqugit** [huyingxi/Synonyms#53]
# description

飞碟: ('魔方', 0.48614)
飞碟: ('中国广播公司', 0.471286)
飞碟: ('台湾电视公司', 0.466064)
飞碟: ('台视', 0.462167)
飞碟: ('中视', 0.446324)
飞碟: ('气球', 0.441919)
飞碟: ('手动式', 0.441638)
飞碟: ('TVBS', 0.440763)
飞碟: ('中广', 0.433497)

## expected

# solution

# environment

* version:
The commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
我的测试结果和你的不同，请说明版本和测试的代码。

![image](https://user-images.githubusercontent.com/3538629/37190591-ace669ce-2395-11e8-9e61-666bbc663e99.png)

**Comment by liqugit** [comment]
老师，您好！

我是根据您git主页的帮助文档，在Anaconda 3 下面3月2日也就是上周五采用pip install -U synonyms 在windows7下安装成功的。使用的python版本是3.6.0.测试代码如图：

我没有找到synonyms.__version__字段。但是在文件中找到如下信息
# File: /Users/hain/ai/Synonyms/synonyms/__init__.py 
# Author: Hai Liang Wang 
# Date: 2017-09-27 

不知道具体是什么原因。
感谢您的辛勤劳动和帮助！

祝好！




liqu
 
发件人： Samurais
发送时间： 2018-03-09 12:31
收件人： huyingxi/Synonyms
抄送： liqu; Author
主题： Re: [huyingxi/Synonyms] 飞碟的同义词怎么会有多个类型的词汇？ (#53)
我的测试结果和你的不同，请说明版本和测试的代码。

**Comment by Samurais** [comment]
hi, 

使用 3.3.9 版本，3.3.6是又bug。 
```
pip install -U synonyms
```
