### ISSUE TITLE
请问下相似度计算公式是什么？

### ISSUE THREAD

**Issue by Wall-ee** [huyingxi/Synonyms#56]
请问下相似度计算公式是什么？

目前我用的多的是textrank + word2vec 
请问本工具的算法是？我想做下对比，可能的话我把我的算法也pr过来

**Comment by Samurais** [comment]
两个句子使用textrank是怎么计算相似度呢？
是将分词后的结构构图，然后词和词之间投票么？

现在 Synonyms 使用将编辑距离和词向量距离融合的方式。

**Comment by Wall-ee** [comment]
啊 我理解了 你现在用的就是 TFIDF 权重乘以word2vec的余弦距离吧？我差不多 只不过权重的计算方式用的是TextRank 。 weight *每个词的向量 然后计算加权后的余弦距离
