### ISSUE TITLE
enhance Synonyms#compare

### ISSUE THREAD

**Issue by Samurais** [huyingxi/Synonyms#6]
# description
use advanced method to compute similarity for two sentence.

related with #4 

# solution
leverage adv distance measurements.

**Comment by Samurais** [comment]
# distance 计算方式比较

![image](https://user-images.githubusercontent.com/3538629/32133244-bd8a4ef8-bb99-11e7-9c36-dc2e59d01e39.png)

![image](https://user-images.githubusercontent.com/3538629/32133246-c2bb6402-bb99-11e7-86ab-a78c0f7c9b0b.png)

![image](https://user-images.githubusercontent.com/3538629/32133247-c9532c6e-bb99-11e7-9353-710356f99155.png)

From https://lyfat.wordpress.com/2012/05/22/euclidean-vs-chebyshev-vs-manhattan-distance/

**Comment by huyingxi** [comment]
Thanks .
I have tested on several different similarity measures, and found that Euclidean distance is the best.
And I merged some other features such as synonys' word embeddings , unigram overlap, POS tag ...

**Comment by Samurais** [comment]
Commit c0a477555174baa5f5c03243c3bea79aa206b8e9

**Comment by huyingxi** [comment]
![roc_curve_eulidean0 8 unigram0 2 pos](https://user-images.githubusercontent.com/15273969/32412323-eac99396-c1c1-11e7-9e95-f38fee63f85d.png)
I just test on the 778 pairs of sentences (link: https://github.com/fssqawj/SentenceSim/blob/master/dev.txt)

and get these curves:
![pr_hresholds_eulidean0 8 unigram0 2 pos](https://user-images.githubusercontent.com/15273969/32412320-e444cf36-c1c1-11e7-88aa-3d180c19ee78.png)
