### ISSUE TITLE
compare函数的问题

### ISSUE THREAD

**Issue by jreros** [huyingxi/Synonyms#60]
调用compare函数时，交换sen1和sen2的值，得到差异很大的结果，例如：

>>> synonyms.compare("教学", "老师")
0.879
>>> synonyms.compare("老师", "教学")
0.194

**Comment by Samurais** [comment]
@jreros , @huyingxi  做了一个提交。
简单说，两个句子内部使用有顺序，现在yingxi已经优化了。
在测试通过后，会发布在下一个版本中。
Thanks.

**Comment by Samurais** [comment]
@huyingxi 
现在你的修改，使得计算量增加不少。有更简单的方案。

**Comment by Samurais** [comment]
Fixed in v3.6
