### ISSUE TITLE
out of vocabulary

### ISSUE THREAD

**Issue by GitOad** [huyingxi/Synonyms#61]
# description
分词分出“多少钱”的词性为n，查找同义词时synonyms.display("多少钱")返回out of vocabulary，查看文件vocab.txt中有一条记录为 多少钱 3 nr，请问是哪里出了问题
## expected

# solution

# environment

* version:
The commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
vocab.txt 是在分词中，不代表着也在 词向量词表中。
当前，词向量词表中没有这个词。
