### ISSUE TITLE
words.vector是怎么训练出来的，里面的参数是如何设置的？

### ISSUE THREAD

**Issue by wwf6688** [huyingxi/Synonyms#63]
# description
words.vector是怎么训练出来的，里面的参数是如何设置的？
## current
无
## expected

# solution

# environment

* version:
The commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
请参考 https://github.com/Samurais/wikidata-corpus

**Comment by myenglishmail** [comment]
有介绍页面，测试语句相似度，所使用的词向量文件吗？
我的相似度，比较低
