### ISSUE TITLE
遇到一个问题，求解答

### ISSUE THREAD

**Issue by fanzfeng** [huyingxi/Synonyms#65]
## 描述
1. 词相似度计算结果出现nan的情况
![image](https://user-images.githubusercontent.com/16243193/41648440-755403a6-74ab-11e8-9f01-ba27a92a008d.png)

## 版本与硬件信息
1. synonyms 3.6.0
1. Python 3.6.4
1. macOS 10.13.3

**Comment by Samurais** [comment]
看上去是numpy的版本问题。

版本

```
Python 3.6.1
numpy==1.14.1
```
运行没有问题

![image](https://user-images.githubusercontent.com/3538629/41690727-783d07a6-7529-11e8-8fd3-f2822cb9a68c.png)

**Comment by fanzfeng** [comment]
已经更新numpy到1.14.1，问题解决了，谢谢~
