### ISSUE TITLE
所以这是一个离线的word2vec模型么？

### ISSUE THREAD

**Issue by jotline** [huyingxi/Synonyms#67]
训练集大概有多大？可以增量训练么？

**Comment by xuhaifeng017** [comment]
@jotline 你有没有出现这个问题
![image](https://user-images.githubusercontent.com/32606897/45279446-b326e480-b503-11e8-98cc-efe0892c331e.png)

**Comment by jotline** [comment]
@xuhaifeng017 我目前没出现问题。我直接在centos下用pip安装的，我没在windows下运行过，也没试过demo.py这个例子。
