### ISSUE TITLE
python3.7安装失败

### ISSUE THREAD

**Issue by dik111** [huyingxi/Synonyms#70]
Command "d:\ananconda3.7\python.exe -u -c "import setuptools, tokenize;__file__=
'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-_fik_53j\\scipy\\setup.p
y';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n
');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\AD
MINI~1\AppData\Local\Temp\pip-record-wmbohszk\install-record.txt --single-versio
n-externally-managed --compile --user --prefix=" failed with error code 1 in C:\
Users\ADMINI~1\AppData\Local\Temp\pip-install-_fik_53j\scipy\

**Comment by callzhang** [comment]
同问

**Comment by ipydeal** [comment]
原因应该是 scipy1.0.0版本 不支持python3.7

**Comment by Samurais** [comment]
支持3.7，默认开发环境就是python 3.7.
