### ISSUE TITLE
安装问题，求助。

### ISSUE THREAD

**Issue by laurentzz** [huyingxi/Synonyms#71]
# description
我用python3.7，用pip3 install synonyms的时候遇到了错误：

Command "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/hs/_5dd__2506j6nrdppdwdhv4c0000gn/T/pip-install-x50s8_ag/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/hs/_5dd__2506j6nrdppdwdhv4c0000gn/T/pip-record-c1tz298g/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/hs/_5dd__2506j6nrdppdwdhv4c0000gn/T/pip-install-x50s8_ag/scipy/

安装过程中，scipy，scikit-learn和absl-py都要安装，而这几个包我已经装了最新版本。
我觉得出错在scipy的安装上，因为我电脑上有scipy最新版本 scipy-1.1.0，但安装过程中，terminal上显示的是uninstall existing scipy-1.1.0，然后又python set.py... 就在这个过程中出错了....

烦请帮助解决，谢谢~

* version:
The commit hash (`git rev-parse HEAD`)

**Comment by yewenjunfighting** [comment]
个人建议：如果提醒pip升级，就把pip升级后重新安装
                  如果还不行就装个python3.6.5的，然后把pip升级到最新版本，我是这样才安装起来的

**Comment by Samurais** [comment]
使用最新的 Synonyms 3.10.2+ 版本。
