### ISSUE TITLE
查“小康”的近义词出现了HTML标签和英文单词

### ISSUE THREAD

**Issue by kuangthree** [huyingxi/Synonyms#73]
synonyms.display('小康')
'小康'近义词：
  1. 小康:1.0
  2. 新时期:0.505846
  3. 中心镇:0.471591
  4. 书香:0.471404
  5. 家境贫寒:0.471054
  6. 下乡:0.443652
  7. 三代人:0.424502
  8. 玉溪:0.416268
  9. </s>:0.0780543
  10. Pardosa:0.0624822

**Comment by Samurais** [comment]
目前会将最接近这个词的前10个展示出来，但是不代表都是近义词。
需要结合相似度分数，比如 Pardosa的相似度是0.0624822.

相似度是0-1的置信区间，0完全相似，1完全一致，也就是越接近1越相似。
