### ISSUE TITLE
请问 google 的 bert 的模型和 word2vec 比会得到更好的效果吗？

### ISSUE THREAD

**Issue by crapthings** [huyingxi/Synonyms#74]
google bert 也能用来做近似词吗？

google bert 提供了一个中文的 pretained 模型可以用来像  fasttext 那样做nearest-neighbor-queries吗？

**Comment by xf739645524** [comment]
请问 google 的 bert 的模型和 word2vec 比会得到更好的效果吗？

**Comment by Samurais** [comment]
会

**Comment by HanelYuki** [comment]
这个取决于训练语料。 bert拟合能力理论上强于word2vec，但是奈何google提供的预训练模型已经定了，除了你自己去finetune，不然在 垂直领域上的语言模型效果优化上，word2vec这种轻量级的算法，能立马落地，bert却不能；另外，xlnet的语言建模能力也会强于bert。 其实，bert强在它可以作为其它模型的地基，而不是它提供了多么准确的词向量表征。
