### ISSUE TITLE
类似问题再次出现

### ISSUE THREAD

**Issue by ridethepig** [huyingxi/Synonyms#75]
# description
再次出现nan的问题
## current  
>PS C:\WINDOWS\system32> python
Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
\>\>\> import synonyms
\>\> Synonyms load wordseg dict [C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\synonyms\data\vocab.txt] ...
\>\> Synonyms on loading stopwords [C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\synonyms\data\stopwords.txt] ...
\>\> Synonyms on loading vectors [C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\synonyms\data\words.vector] ...
\>\>\> synonyms.compare("上面","下面")
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\synonyms\utils.py:246: RuntimeWarning: invalid value encountered in double_scalars
  cosine = lambda a, b: dot(a, b)/(norm(a)*norm(b))
nan

## expected

# solution
感觉可能需要改进一下数据集了  
或者干脆不建议比较某些类型的词
# environment
Windows 10 x64
python 3.6.6
numpy 1.16.1

* version:
> \>\>\> synonyms.__version__
'3.3.10'

**Comment by Samurais** [comment]
需要改进，引入基于字形等形式。
