### ISSUE TITLE
absl-py version conflict

### ISSUE THREAD

**Issue by andyxzq** [huyingxi/Synonyms#77]
# description
synonyms依赖absl-py=0.1.10，但tensorflow1.13.1依赖absl-py>=0.4，无法共存。
## expected
升级absl-py到0.4版本以上
# solution

# environment
ubuntu16.04，linux4.4.0，python2.7
* version:
The commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
Fixed since Release synonyms-3.10.2
