### ISSUE TITLE
相似度计算方法，结果不一致

### ISSUE THREAD

**Issue by AlexYoung757** [huyingxi/Synonyms#80]
句子相似度比较每次得到的结果居然不一致。。。
第一次运行结果：
相似度：1.0
相似度：0.304
相似度：0.626

第二次运行结果：
相似度：1.0
相似度：0.326
相似度：0.635

第三次运行结果：
相似度：1.0
相似度：0.291
相似度：0.618

**Comment by Samurais** [comment]
OOV词汇生成随机向量。
