### ISSUE TITLE
相似度效果是真差

### ISSUE THREAD

**Issue by zhangxuanaj** [huyingxi/Synonyms#83]
sen1 = "美人鱼2暑期上映"
sen2 = "迷你世界：就算今天是愚人节，也不带这样整人的啊！"
r = synonyms.compare(sen1, sen2, seg=True)
r: 0.341

sen1 = "身份证定位"
sen2 = "正向盈利和逆向盈利的区别"
r = synonyms.compare(sen1, sen2, seg=True)
r: 0.401

sen1 = "巴黎圣母院大火"
sen2 = "痛啊！八百五十多年历史的巴黎圣母院，付之一炬大火吞噬"
r = synonyms.compare(sen1, sen2, seg=True)
r: 0.357

还有非常非常多的bad case， 根本不能用

**Comment by Samurais** [comment]
以上各个case，你觉得合理的相似度应该是多少？

**Comment by chaotianjiao** [comment]
@zhangxuanaj  这位暴躁老哥，你可以反馈BUG，但请端正你的态度，人家开源出来给你用就不错了，嫌不好用自己动手写一个啊，在这里当键盘侠有什么意思？
